### ISSUE TITLE
BUG: Ansible complains about using sed manually in the role definition.

### ISSUE THREAD

**Issue by SteveParson** [SteveParson/xubuntu-18.04-dev-box#1]
**Describe the bug**
Ansible complains about using `sed` manually in the role definition.

**To Reproduce**
Create a new VM and watch the output from Ansible.

**Expected behavior**
I would expect Ansible to not complain about this.

**Screenshots**
![image](https://user-images.githubusercontent.com/20347119/54573946-b9bb7a80-49c4-11e9-8e18-dd32453eb236.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29

**Additional context**
Need to port
```
- name: Fix xrdp
  shell: "sed -i 's/new_cursors=true/new_cursors=false/g' /etc/xrdp/xrdp.ini"
  become: yes
``` 
to use `lineinfile`

**Comment by anihm136** [comment]
I'd like to work on this, if it's still open

**Comment by SteveParson** [comment]
I'd be happy to accept your pull request!

**Comment by anihm136** [comment]
I've created a PR with a new branch to fix this. Check it out and let me know if it works as expected
