### ISSUE TITLE
FEATURE: Add shortcuts for Pycharm and IntelliJ IDEA

### ISSUE THREAD

**Issue by SteveParson** [SteveParson/xubuntu-18.04-dev-box#4]
**Is your feature request related to a problem? Please describe.**
Both Pycharm and IntelliJ IDEA are installed to `/usr/local/bin`. Currently there is no shortcut to these programs in the GUI.

**Describe the solution you'd like**
 In order to be useful, there needs to be a shortcut present to these programs.

**Comment by SteveParson** [comment]
If someone were to edit the Ansible role to add these two files to `/home/vagrant/Desktop`, we would be in business.
```
vagrant@xubuntu:~/Desktop$ cat IntelliJ\ IDEA.desktop 
[Desktop Entry]
Version=1.0
Type=Application
Name=IntelliJ IDEA
Comment=
Exec=/usr/local/bin/idea-IC-183.5912.21/bin/idea.sh
Icon=/usr/local/bin/idea-IC-183.5912.21/bin/idea.png
Path=
Terminal=false
StartupNotify=false

vagrant@xubuntu:~/Desktop$ cat PyCharm.desktop 
[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm
Comment=
Exec=/usr/local/bin/pycharm-community-2018.3.5/bin/pycharm.sh
Icon=/usr/local/bin/pycharm-community-2018.3.5/bin/pycharm.png
Path=
Terminal=false
StartupNotify=false
```
It would also be nice to adjust the files list under `Exec` to have the executable bit set, to avoid this ugly message.
![image](https://user-images.githubusercontent.com/20347119/54575396-57fe0f00-49ca-11e9-8797-5768f3f133d3.png)

**Comment by arjunvkurup** [comment]
The best way to resolve this problem is to create an executable file. 
```shell
chmod +x IDEA.desktop
chmod +x pycharm.desktop
```
and then try running the shortcuts again.

If this issue is still there, Can I work on it?

**Comment by SteveParson** [comment]
Absolutely! Feel free to send me a pull request!

**Comment by SteveParson** [comment]
No longer relevant as per https://github.com/SteveParson/xubuntu-18.04-dev-box/pull/9
