### ISSUE TITLE
FEATURE: Automatically download the latest versions of IntelliJ IDEA and Pycharm

### ISSUE THREAD

**Issue by SteveParson** [SteveParson/xubuntu-18.04-dev-box#5]
**Is your feature request related to a problem? Please describe.**
Currently, IntelliJ IDEA and Pycharm are being downloaded from fixed URLs.

**Describe the solution you'd like**
I would like [this link](https://www.jetbrains.com/idea/download/download-thanks.html?platform=linux&code=IIC) to be scraped for the correct download link to the latest version. Ditto for Pycharm. They could be extracted to static names in `/usr/local/bin`, such as:
- `/usr/local/bin/pycharm`
- `/usr/local/bin/intellij`

**Describe alternatives you've considered**
This is just *nice-to-have*, but would be easy to implement.

**Comment by SteveParson** [comment]
Unfortunately, the product website uses some Javascript to create the links. You could use Selenium to get the latest links, but there is an easier way.

Use whatever you want to parse the JSON from the links below
- Pycharm -> https://data.services.jetbrains.com/products/releases?code=PCC
-- PCC -> 0 -> downloads -> link    (and also checksumLink)
- IntelliJ IDEA -> https://data.services.jetbrains.com/products/releases?code=IIC
-- IIC -> 0 -> downloads -> link    (and also checksumLink)

Pass the results of your script to Ansible, so that it can download the IDEs.
Consider extracting to a static directory name like  `idea` instead of `ideaIC-2019.1`, since we intend to add shortcuts to the desktop for both of these IDEs. In that case, the directory names won't change, so the shortcuts can be a static file.

**Comment by raunaqness** [comment]
@SteveParson I'm interested in this. Can i contribute?

**Comment by SteveParson** [comment]
One of the PRs (which I haven't finished reviewing) have changed this to use the snap package instead, which is a pretty good solution. I will most likely go with that, but if you have any other ideas I'd be happy to hear them.

**Comment by raunaqness** [comment]
I was thinking of going with apt (or something similar). Let me know If the PR does not work out for you or If I can help out some other way. Thanks!

**Comment by SteveParson** [comment]
Fixed in https://github.com/SteveParson/xubuntu-18.04-dev-box/pull/9
