### ISSUE TITLE
FEATURE: Automatically install Virtualbox Extension Pack and the Guest Additions ISO

### ISSUE THREAD

**Issue by SteveParson** [SteveParson/xubuntu-18.04-dev-box#6]
**Is your feature request related to a problem? Please describe.**
The Virtualbox extension pack is not automatically provisioned, nor is the guest additions ISO. The former adds extra functionality like USB 3.0, PXE, VDRP, and disk image encryption. The latter is needed to supply hosts with the drivers necessary for a seamless experience.

**Describe the solution you'd like**
I would like to have these automatically installed via Ansible. These are provided by the following two packages
- virtualbox-ext-pack
- virtualbox-guest-additions-iso

There is a challenge when installing `virtualbox-ext-pack` in that it requires a license to be accepted. This is a challenge from the perspective of ansible script. The package `expect` can help us with this. Installed as a prerequisite, we can script the license acceptance step with something like
```
#!/usr/bin/expect -f
set timeout -1
spawn apt-get install virtualbox-ext-pack
expect "a string from the first screen"
send -- "\t\r\n"
expect "a string from the second screen" 
send -- "\t\r\n"
expect eof
```
**Describe alternatives you've considered**

**Additional context**

**Comment by dangarthwaite** [comment]
I assume you want these extra downloads to be optional?

ansible 2.0 has the expect module

**Comment by dangarthwaite** [comment]
Happy Hactoberfest

**Comment by SteveParson** [comment]
Thanks! Fixed in https://github.com/SteveParson/xubuntu-18.04-dev-box/pull/11
